# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.synced_folder  ".", "/vagrant", disabled: false
  config.vm.network "private_network", ip: "192.168.33.36"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
    sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
    echo "alias ll='ls -la'" >> /root/.bashrc
    rm /usr/bin/python
    ln -s /usr/bin/python3.7 /usr/bin/python
    apt update && apt install -y python3-pip
    ln -s /usr/bin/pip3 /usr/bin/pip
  SHELL
end
