# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.box_check_update = false

  config.vm.define "jenkins.vm" do |jvm|
    jvm.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    jvm.vm.network "private_network", ip: "192.168.50.10"
    jvm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus   = "2"
      vb.name   = "jenkins.vm"
    end
  end

  config.vm.define "nexus.vm" do |nvm|
    nvm.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1"
    nvm.vm.network "private_network", ip: "192.168.50.11"
    nvm.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus   = "1"
      vb.name   = "nexus.vm"
    end
  end

  config.vm.define "staging.vm" do |svm|
    svm.vm.network "forwarded_port", guest: 8888, host: 8889, host_ip: "127.0.0.1"
    svm.vm.network "private_network", ip: "192.168.50.20"
    svm.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus   = "1"
      vb.name   = "staging.vm"
    end
  end

  config.vm.define "node1.vm" do |n1|
    n1.vm.network "private_network", ip: "192.168.50.30"
    n1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus   = "1"
      vb.name   = "node1.vm"
    end
  end

  config.vm.define "node2.vm" do |n2|
    n2.vm.network "private_network", ip: "192.168.50.31"
    n2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus   = "1"
      vb.name   = "node2.vm"
    end
  end

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = "provisioning/playbook.yaml"
    ansible.inventory_path = "provisioning/hosts"
    ansible.galaxy_role_file = "provisioning/requirements.yaml"
  end
end
