# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.box_check_update = false

  hosts = [
    { name: "jenkins", forwarded_port: { guest: 8080, host: 8080 }, private_network: { ip: "192.168.50.10" }, memory: 1024, cpus: 2 },
    { name: "nexus", forwarded_port: { guest: 8081, host: 8081 }, private_network: { ip: "192.168.50.11" }, memory: 2048, cpus: 1 },
    { name: "staging", forwarded_port: { guest: 8888, host: 8889 }, private_network: { ip: "192.168.50.20" }, memory: 512, cpus: 1 },
    { name: "production", forwarded_port: { guest: 8888, host: 8888 }, private_network: { ip: "192.168.50.21" }, memory: 512, cpus: 1 },
    { name: "node1", private_network: { ip: "192.168.50.30" }, memory: 512, cpus: 1 },
    { name: "node2", private_network: { ip: "192.168.50.31" }, memory: 512, cpus: 1 }
  ]

  hosts.each do |host|
    config.vm.define "#{host[:name]}.vm" do |hvm|
      hvm.vm.network :forwarded_port, host[:forwarded_port] if host.key? :forwarded_port
      hvm.vm.network :private_network, host[:private_network] if host.key? :private_network
      hvm.vm.provider :virtualbox do |vb|
        vb.memory = host[:memory] || 512
        vb.cpus   = host[:cpus]   || 1
        vb.name   = "#{host[:name]}.vm"
      end
    end
  end

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = "provisioning/playbook.yaml"
    ansible.inventory_path = "provisioning/hosts"
    ansible.galaxy_role_file = "provisioning/requirements.yaml"
  end
end
